<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#[round()]数字的四舍五入" data-toc-modified-id="[round()]数字的四舍五入-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>[round()]数字的四舍五入</a></span><ul class="toc-item"><li><span><a href="#讨论" data-toc-modified-id="讨论-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>讨论</a></span></li></ul></li><li><span><a href="#[decimal.Decimal()]执行精确的浮点数运算" data-toc-modified-id="[decimal.Decimal()]执行精确的浮点数运算-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>[decimal.Decimal()]执行精确的浮点数运算</a></span><ul class="toc-item"><li><span><a href="#讨论" data-toc-modified-id="讨论-2.1"><span class="toc-item-num">2.1&nbsp;&nbsp;</span>讨论</a></span></li></ul></li><li><span><a href="#[format()-{0.2f->10.1f-,e}]数字的格式化输出" data-toc-modified-id="[format()-{0.2f->10.1f-,e}]数字的格式化输出-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>[format() {0.2f &gt;10.1f ,e}]数字的格式化输出</a></span></li><li><span><a href="#二八十六进制整数" data-toc-modified-id="二八十六进制整数-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>二八十六进制整数</a></span></li><li><span><a href="#[int.to_bytes-int.from_bytes]字节到大整数的打包与解包" data-toc-modified-id="[int.to_bytes-int.from_bytes]字节到大整数的打包与解包-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>[int.to_bytes int.from_bytes]字节到大整数的打包与解包</a></span></li><li><span><a href="#[cmath-numpy]复数的数学运算" data-toc-modified-id="[cmath-numpy]复数的数学运算-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>[cmath numpy]复数的数学运算</a></span></li><li><span><a href="#[math.isinf()-float('inf')]无穷大与NaN" data-toc-modified-id="[math.isinf()-float('inf')]无穷大与NaN-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>[math.isinf() float('inf')]无穷大与NaN</a></span><ul class="toc-item"><li><span><a href="#讨论" data-toc-modified-id="讨论-7.1"><span class="toc-item-num">7.1&nbsp;&nbsp;</span>讨论</a></span></li></ul></li><li><span><a href="#[fractions.Fraction]分数运算" data-toc-modified-id="[fractions.Fraction]分数运算-8"><span class="toc-item-num">8&nbsp;&nbsp;</span>[fractions.Fraction]分数运算</a></span></li><li><span><a href="#[numpy]大型数组运算" data-toc-modified-id="[numpy]大型数组运算-9"><span class="toc-item-num">9&nbsp;&nbsp;</span>[numpy]大型数组运算</a></span></li><li><span><a href="#[np.matrix-numpy.linalg]矩阵与线性代数运算" data-toc-modified-id="[np.matrix-numpy.linalg]矩阵与线性代数运算-10"><span class="toc-item-num">10&nbsp;&nbsp;</span>[np.matrix numpy.linalg]矩阵与线性代数运算</a></span></li><li><span><a href="#[random]随机选择" data-toc-modified-id="[random]随机选择-11"><span class="toc-item-num">11&nbsp;&nbsp;</span>[random]随机选择</a></span><ul class="toc-item"><li><span><a href="#[seed]讨论" data-toc-modified-id="[seed]讨论-11.1"><span class="toc-item-num">11.1&nbsp;&nbsp;</span>[seed]讨论</a></span></li></ul></li><li><span><a href="#[datetime]基本的日期与时间转换" data-toc-modified-id="[datetime]基本的日期与时间转换-12"><span class="toc-item-num">12&nbsp;&nbsp;</span>[datetime]基本的日期与时间转换</a></span><ul class="toc-item"><li><span><a href="#[dateutil.relativedelta]讨论" data-toc-modified-id="[dateutil.relativedelta]讨论-12.1"><span class="toc-item-num">12.1&nbsp;&nbsp;</span>[dateutil.relativedelta]讨论</a></span></li></ul></li><li><span><a href="#计算最后一个周五的日期" data-toc-modified-id="计算最后一个周五的日期-13"><span class="toc-item-num">13&nbsp;&nbsp;</span>计算最后一个周五的日期</a></span><ul class="toc-item"><li><span><a href="#[dateutil]讨论" data-toc-modified-id="[dateutil]讨论-13.1"><span class="toc-item-num">13.1&nbsp;&nbsp;</span>[dateutil]讨论</a></span></li></ul></li><li><span><a href="#[calendar]计算当前月份的日期范围" data-toc-modified-id="[calendar]计算当前月份的日期范围-14"><span class="toc-item-num">14&nbsp;&nbsp;</span>[calendar]计算当前月份的日期范围</a></span></li><li><span><a href="#[datetime.strptime()]字符串转换为日期" data-toc-modified-id="[datetime.strptime()]字符串转换为日期-15"><span class="toc-item-num">15&nbsp;&nbsp;</span>[datetime.strptime()]字符串转换为日期</a></span></li><li><span><a href="#结合时区的日期操作" data-toc-modified-id="结合时区的日期操作-16"><span class="toc-item-num">16&nbsp;&nbsp;</span>结合时区的日期操作</a></span><ul class="toc-item"><li><span><a href="#讨论" data-toc-modified-id="讨论-16.1"><span class="toc-item-num">16.1&nbsp;&nbsp;</span>讨论</a></span></li></ul></li></ul></div>

# [round()]数字的四舍五入

`round(value, ndigits)`

In [1]:

# 小數
round(1.27, 1)

round(-1.27, 1)

round(1.25361,3)

# 大數取整
a = 1627731

round(a, -1)

round(a, -3)

1.3

-1.3

1.254

## 讨论

格式化只改變顯示，內容未變

In [2]:
x = 1.23456
format(x, '0.2f') # '1.23'
format(x, '0.3f') # '1.235'
'value is {:0.3f}'.format(x) # 'value is 1.235'

'1.23'

'1.235'

'value is 1.235'

# [decimal.Decimal()]执行精确的浮点数运算

**浮点数**的一个普遍问题是它们并不能精确的表示十进制数。 并且，即使是最简单的数学运算也会产生**小的误差**

这些错误是由底层`CPU`和`IEEE 754`标准通过自己的浮点单位去执行算术时的特征。 由于`Python`的浮点数据类型使用底层表示存储数据，因此你没办法去避免这样的误差。

In [4]:
a = 4.2
b = 2.1
a + b
(a + b) == 6.3

6.300000000000001

False

**更加精确(并能容忍一定的性能损耗)**

In [6]:
from decimal import Decimal

a = Decimal('4.2')
b = Decimal('2.1')

a + b

(a + b) == Decimal('6.3')


Decimal('6.3')

True

`decimal` 模块的一个主要特征是允许你控制计算的每一方面，包括数字位数和四舍五入运算。 为了这样做，你先得创建一个本地上下文并更改它的设置，比如：

In [7]:
from decimal import localcontext

a = Decimal('1.3')
b = Decimal('1.7')
print(a / b)

with localcontext() as ctx:
    ctx.prec = 3
    print(a / b)
    
with localcontext() as ctx:
    ctx.prec = 50
    print(a / b)

0.7647058823529411764705882353
0.765
0.76470588235294117647058823529411764705882352941176


## 讨论

即便如此，你却不能完全忽略误差

你也得注意下减法删除以及大数和小数的加分运算所带来的影响。

In [8]:
nums = [1.23e+18, 1, -1.23e+18]
sum(nums) # Notice how 1 disappears

0.0

上面的错误可以利用 `math.fsum()` 所提供的更精确计算能力来解决

In [9]:
import math

nums = [1.23e+18, 1, -1.23e+18]
math.fsum(nums)

1.0

# [format() {0.2f >10.1f ,e}]数字的格式化输出

`format()` 


* `0.2f` 
* `>10.1f` 
* `,` 
* `e`

In [20]:
x = 1234.56789

# Two decimal places of accuracy
format(x, '0.2f') # '1234.57'

# Right justified in 10 chars, one-digit accuracy
format(x, '>10.1f') # '    1234.6'

# Left justified
format(x, '<10.1f') # '1234.6    '

# Centered
format(x, '^10.1f') # '  1234.6  '

# Inclusion of thousands separator
format(x, ',') # '1,234.56789'
format(x, '0,.1f') # '1,234.6'


format(x, 'e') # '1.234568e+03'
format(x, '0.2E') # '1.23E+03'

'%0.2f' % x # '1234.57'
'%10.1f' % x # '    1234.6'
'%-10.1f' % x # '1234.6    '

'1234.57'

'    1234.6'

'1234.6    '

'  1234.6  '

'1,234.56789'

'1,234.6'

'1.234568e+03'

'1.23E+03'

'1234.57'

'    1234.6'

'1234.6    '

同时指定宽度和精度的一般形式是 `'[<>^]?width[,]?(.digits)?'` ， 其中 `width` 和 `digits` 为整数，`？`代表可选部分。 同样的格式也被用在字符串的 `format()` 方法中

In [15]:
'The value is {:>10,.2f}'.format(x)

'The value is   1,234.57'

包含**千位符**的格式化跟本地化没有关系。 如果你需要根据地区来显示千位符，你需要自己去调查下 `locale` 模块中的函数了。 你同样也可以使用字符串的 `translate()` 方法来交换千位符。

In [19]:
swap_separators = { ord('.'):',', ord(','):'.' }
format(x, ',').translate(swap_separators)

'1.234,56789'

# 二八十六进制整数

为了将整数转换为二进制、八进制或十六进制的文本串， 可以分别使用 `bin()` , `oct()` 或 `hex()`

In [21]:
x = 1234
bin(x) # '0b10011010010'
oct(x) # '0o2322'
hex(x) # '0x4d2'

'0b10011010010'

'0o2322'

'0x4d2'

如果你不想输出 `0b` , `0o` 或者 `0x` 的前缀的话，可以使用 `format()` 函数。

In [22]:
x = 1234

format(x, 'b') # '10011010010'
format(x, 'o') # '2322'
format(x, 'x') # '4d2'

# 轉換進制
int('4d2', 16) # 1234
int('10011010010', 2) # 1234


'10011010010'

'2322'

'4d2'

需确保八进制数的前缀是 `0o`

# [int.to_bytes int.from_bytes]字节到大整数的打包与解包

假设你的程序需要处理一个拥有128位长的16个元素的字节字符串

In [23]:
data = b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

len(data) # 16

int.from_bytes(data, 'little')

int.from_bytes(data, 'big')

x = 94522842520747284487117727783387188
x.to_bytes(16, 'big')# b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'
x.to_bytes(16, 'little')# b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'



16

69120565665751139577663547927094891008

94522842520747284487117727783387188

b'\x00\x124V\x00x\x90\xab\x00\xcd\xef\x01\x00#\x004'

b'4\x00#\x00\x01\xef\xcd\x00\xab\x90x\x00V4\x12\x00'

**字节顺序规则('little'或'big')** 仅仅指定了构建整数时的字节的低位高位排列方式。

In [24]:
x = 0x01020304
x.to_bytes(4, 'big') # b'\x01\x02\x03\x04'
x.to_bytes(4, 'little') # b'\x04\x03\x02\x01'

b'\x01\x02\x03\x04'

b'\x04\x03\x02\x01'

**超大數** 

可以使用 `int.bit_length()` 方法来决定需要多少字节位来存储这个值。

In [25]:
x = 523 ** 23
x

335381300113661875107536852714019056160355655333978849017944067

In [26]:
x.to_bytes(16, 'little')

OverflowError: int too big to convert

In [27]:
x.bit_length() # 208

nbytes, rem = divmod(x.bit_length(), 8)

if rem:
    nbytes += 1
    
x.to_bytes(nbytes, 'little')

208

b'\x03X\xf1\x82iT\x96\xac\xc7c\x16\xf3\xb9\xcf\x18\xee\xec\x91\xd1\x98\xa2\xc8\xd9R\xb5\xd0'

# [cmath numpy]复数的数学运算

In [29]:
# 建構復數
a = complex(2, 4)
# 以j表示復數
b = 3 - 5j
a
b

# 实部、虚部和共轭复数
a.real # 2.0
a.imag # 4.0
a.conjugate() # (2-4j)

(2+4j)

(3-5j)

2.0

4.0

(2-4j)

In [30]:
import cmath

cmath.sin(a)
cmath.cos(a)
cmath.exp(a)

(24.83130584894638-11.356612711218174j)

(-11.36423470640106-24.814651485634187j)

(-4.829809383269385-5.5920560936409816j)

In [31]:
import numpy as np

a = np.array([2+3j, 4+5j, 6-7j, 8+9j])

np.sin(a)

array([   9.15449915  -4.16890696j,  -56.16227422 -48.50245524j,
       -153.20827755-526.47684926j, 4008.42651446-589.49948373j])

# [math.isinf() float('inf')]无穷大与NaN

In [32]:
a = float('inf')
b = float('-inf')
c = float('nan')

a
b
c

inf

-inf

nan

In [33]:
math.isinf(a) # True
math.isnan(c) # True

True

True

## 讨论

想了解更多这些特殊浮点值的信息，可以参考**IEEE 754规范**。 然而，也有一些地方需要你特别注意，特别是跟比较和操作符相关的时候

In [36]:
a = float('inf')

a + 45 # inf
a * 10 # inf
10 / a # 0.0

# 有些操作时未定义的并会返回一个NaN结果
a = float('inf')
a/a # nan

b = float('-inf')
a + b # nan

# NaN值会在所有操作中传播，而不会产生异常
c = float('nan')
c + 23 # nan
c / 2 # nan
c * 2 # nan

# NaN值的一个特别的地方时它们之间的比较操作总是返回False
c = float('nan')
d = float('nan')
c == d # False
c is d # False

inf

inf

0.0

nan

nan

nan

nan

nan

False

False

# [fractions.Fraction]分数运算

In [38]:
from fractions import Fraction

a = Fraction(5, 4)
b = Fraction(7, 16)
print(a + b) # 27/16
print(a * b) # 35/64

# Getting numerator/denominator
c = a * b
c.numerator # 35
c.denominator # 64

# Converting to a float
float(c) # 0.546875

# Limiting the denominator of a value
print(c.limit_denominator(8)) # 4/7

# Converting a float to a fraction
x = 3.75
y = Fraction(*x.as_integer_ratio())
y # Fraction(15, 4)

27/16
35/64


35

64

0.546875

4/7


Fraction(15, 4)

# [numpy]大型数组运算

**運算 廣播**

In [39]:

# Numpy arrays
import numpy as np

ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])

ax * 2 # array([2, 4, 6, 8])
ax + 10 # array([11, 12, 13, 14])
ax + ay # array([ 6, 8, 10, 12])
ax * ay # array([ 5, 12, 21, 32])

def f(x):
    return 3*x**2 - 2*x + 7

f(ax)

array([2, 4, 6, 8])

array([11, 12, 13, 14])

array([ 6,  8, 10, 12])

array([ 5, 12, 21, 32])

array([ 8, 15, 28, 47])

**切片 索引**

In [44]:
grid = np.zeros(shape=(10000,10000), dtype=float)
grid

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a[1]
a[:,1]
a[1:3, 1:3]
a[1:3, 1:3] += 10
a
np.where(a < 10, a, 10)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

array([5, 6, 7, 8])

array([ 2,  6, 10])

array([[ 6,  7],
       [10, 11]])

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

# [np.matrix numpy.linalg]矩阵与线性代数运算

In [45]:
import numpy as np
m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])
m

# Return transpose
m.T

# Return inverse
m.I

# Create a vector and multiply
v = np.matrix([[2],[3],[4]])
v

m * v

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

matrix([[2],
        [3],
        [4]])

matrix([[ 8],
        [32],
        [ 2]])

In [48]:
import numpy.linalg

# Determinant
numpy.linalg.det(m)

# Eigenvalues
numpy.linalg.eigvals(m)

# Solve for x in mx = v
x = numpy.linalg.solve(m, v)
x

m * x
v

-229.99999999999983

array([-13.11474312,   2.75956154,   6.35518158])

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

matrix([[2.],
        [3.],
        [4.]])

matrix([[2],
        [3],
        [4]])

# [random]随机选择

**隨機抽取**

In [52]:
import random
values = [1, 2, 3, 4, 5, 6]
random.choice(values)
random.choice(values)

random.sample(values, 2)
random.sample(values, 3)

2

1

[4, 5]

[2, 3, 5]

**隨機亂序**

In [53]:
random.shuffle(values)
values

[5, 6, 2, 3, 4, 1]

In [64]:
# 隨機數生成 [0-10] 含 0，10
random.randint(0,10)

# 生成0到1范围内均匀分布的浮点数
random.random()

8

N位随机位(二进制 2^200)的整数，使用 `random.getrandbits()` ：

In [84]:
random.getrandbits(200) / 1.0e+20

1.1165537091382448e+40

## [seed]讨论

**隨機數種子**

In [85]:
random.seed() # Seed based on system time or os.urandom()
random.seed(12345) # Seed based on integer given
random.seed(b'bytedata') # Seed based on byte data

在 `random` 模块中的函数不应该用在和密码学相关的程序中。 如果你确实需要类似的功能，可以使用`ssl`模块中相应的函数。 比如， `ssl.RAND_bytes()` 可以用来生成一个安全的随机字节序列。

# [datetime]基本的日期与时间转换

In [86]:
from datetime import timedelta

a = timedelta(days=2, hours=6)
b = timedelta(hours=4.5)
c = a + b
c.days
c.seconds
c.seconds / 3600
c.total_seconds() / 3600


2

37800

10.5

58.5

In [92]:
import datetime as dt

a = dt.datetime(2012, 9, 23)
print(a + timedelta(days=10))

b = dt.datetime(2012, 12, 21)
d = b - a
d.days

now = dt.datetime.today()
print(now)
print(now + timedelta(minutes=10))


2012-10-03 00:00:00


89

2019-07-05 22:36:38.974639
2019-07-05 22:46:38.974639


在计算的时候，需要注意的是 `datetime` 会自动处理**闰年**

In [94]:
a = dt.datetime(2012, 3, 1)
b = dt.datetime(2012, 2, 28)

a - b

(a - b).days

c = dt.datetime(2013, 3, 1)
d = dt.datetime(2013, 2, 28)
(c - d).days


datetime.timedelta(2)

2

1

## [dateutil.relativedelta]讨论

执行更加复杂的日期操作，比如处理时区，模糊时间范围，节假日计算等等， 可以考虑使用 `dateutil`模块

许多类似的时间计算可以使用 `dateutil.relativedelta()` 函数代替。 但是，有一点需要注意的就是，它会在处理月份(还有它们的天数差距)的时候填充间隙。

In [96]:
# 不支援月份
a = datetime(2012, 9, 23)
a + timedelta(months=1)

TypeError: 'months' is an invalid keyword argument for this function

In [98]:
from dateutil.relativedelta import relativedelta

a = dt.datetime(2012, 3, 1)

a + relativedelta(months=+1)
a + relativedelta(months=+4)

# Time between two dates
b = dt.datetime(2012, 12, 21)
d = b - a
d

d = relativedelta(b, a)
d

d.months

d.days

datetime.datetime(2012, 4, 1, 0, 0)

datetime.datetime(2012, 7, 1, 0, 0)

datetime.timedelta(295)

relativedelta(months=+9, days=+20)

9

20

# 计算最后一个周五的日期

In [104]:
"""
Topic: 最后的周五
Desc :
"""
from datetime import datetime, timedelta

weekdays = ['Monday', 'Tuesday', 'Wednesday', 'Thursday',
            'Friday', 'Saturday', 'Sunday']


def get_previous_byday(dayname, start_date=None):
    
    # 若沒初始日(start_date),則設為今天
    if start_date is None:
        start_date = datetime.today()
        
    # 初始日 星期幾 (0-6) -> (Mon ~ Sun)
    day_num = start_date.weekday()
    # 目標 星期幾 (0-6) -> (一 ~ 日)
    day_num_target = weekdays.index(dayname)
    
    days_ago = (7 + day_num - day_num_target) % 7
    
    if days_ago == 0:
        days_ago = 7
        
    target_date = start_date - timedelta(days=days_ago)
    
    return target_date


datetime(2012, 12, 21).weekday()

get_previous_byday(
    'Sunday', datetime(2012, 12, 21)
)


'\nTopic: 最后的周五\nDesc :\n'

4

datetime.datetime(2012, 12, 16, 0, 0)

## [dateutil]讨论

如果你要像这样执行大量的日期计算的话，你最好安装第三方包 `dateuti` 来代替。 比如，下面是是使用 `dateutil` 模块中的 `relativedelta()` 函数执行同样的计算

In [107]:
from datetime import datetime
from dateutil.relativedelta import relativedelta
from dateutil.rrule import FR

d = datetime.now()
print(d)

# Next Friday
print(d + relativedelta(weekday=FR))

# Last Friday
print(d + relativedelta(weekday=FR(-1)))

2019-07-05 23:18:09.993875
2019-07-05 23:18:09.993875
2019-07-05 23:18:09.993875


# [calendar]计算当前月份的日期范围

In [109]:
from datetime import datetime, date, timedelta

import calendar

def get_month_range(start_date=None):
    
    if start_date is None:
        # 當天(date.today()) 當月第一天().replace(day=1))
        start_date = date.today().replace(day=1)
    #  monthrange(year, month) 當前月份範圍 ; 返回 (0, 月(ex:31))
    _, days_in_month = calendar.monthrange(start_date.year, start_date.month)
    # 下月第一天 + 1 (ex: 1+31 )
    end_date = start_date + timedelta(days=days_in_month)
    
    return (start_date, end_date)

In [110]:
a_day = timedelta(days=1)
first_day, last_day = get_month_range()

while first_day < last_day:
    print(first_day)
    first_day += a_day

2019-07-01
2019-07-02
2019-07-03
2019-07-04
2019-07-05
2019-07-06
2019-07-07
2019-07-08
2019-07-09
2019-07-10
2019-07-11
2019-07-12
2019-07-13
2019-07-14
2019-07-15
2019-07-16
2019-07-17
2019-07-18
2019-07-19
2019-07-20
2019-07-21
2019-07-22
2019-07-23
2019-07-24
2019-07-25
2019-07-26
2019-07-27
2019-07-28
2019-07-29
2019-07-30
2019-07-31


**生成器**

In [116]:
def date_range(start, stop, step):
    while start < stop:
        yield start
        start += step

In [118]:
for d in date_range(
    datetime(2012, 9, 1), datetime(2012,9,2),
    timedelta(hours=6)
):
    print(d)

2012-09-01 00:00:00
2012-09-01 06:00:00
2012-09-01 12:00:00
2012-09-01 18:00:00


# [datetime.strptime()]字符串转换为日期

In [120]:
from datetime import datetime
text = '2012-09-20'
y = datetime.strptime(text, '%Y-%m-%d')
z = datetime(2012, 10, 1)
diff = z - y
diff

datetime.timedelta(11)

`strptime()` 的性能要比你想象中的差很多

如果你已经知道所以日期格式是 `YYYY-MM-DD` ，你可以像下面这样实现一个解析函数：

In [122]:
from datetime import datetime

text = '2012-09-20'

def parse_ymd(s):
    year_s, mon_s, day_s = s.split('-')
    return datetime(int(year_s), int(mon_s), int(day_s))

parse_ymd(text)

datetime.datetime(2012, 9, 20, 0, 0)

# 结合时区的日期操作

In [125]:
from datetime import datetime
from pytz import timezone
d = datetime(2012, 12, 21, 9, 30, 0)
print(d)

# Localize the date for Chicago
# 芝加哥时间
central = timezone('US/Central')
loc_d = central.localize(d)
print(loc_d)

# Convert to Bangalore time
# 轉換時區
bang_d = loc_d.astimezone(timezone('Asia/Kolkata'))
print(bang_d)

2012-12-21 09:30:00
2012-12-21 09:30:00-06:00
2012-12-21 21:00:00+05:30


## 讨论

需要特别注意夏令时转换和其他细节

为了不让你被这些东东弄的晕头转向，处理本地化日期的通常的策略先将所有日期转换为`UTC时间`， 并用它来执行所有的中间存储和操作。

In [128]:
import pytz

print(loc_d)
utc_d = loc_d.astimezone(pytz.utc)
print(utc_d)

later_utc = utc_d + timedelta(minutes=30)
print(later_utc.astimezone(central))

2012-12-21 09:30:00-06:00
2012-12-21 15:30:00+00:00
2012-12-21 10:00:00-06:00


注：当你阅读到这里的时候，有可能 `pytz` 模块已经不再建议使用了，因为PEP431提出了更先进的时区支持。 但是这里谈到的很多问题还是有参考价值的(比如使用UTC日期的建议等)。